<a href="https://colab.research.google.com/github/aletbm/MySolutions_MLZoomcamp2024_DataTalks.Club/blob/main/1_Introduction_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import packages

In [ ]:
import pandas as pd
import numpy as np
from numpy.linalg import inv


# Downloading the dataset



In [ ]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-23 19:16:12--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv.1’

laptops.csv.1       100%[===================>] 291.58K  --.-KB/s    in 0.02s   

2024-09-23 19:16:12 (11.6 MB/s) - ‘laptops.csv.1’ saved [298573/298573]



# Q1. Pandas version
What's the version of Pandas that you installed?



In [ ]:
pd.__version__

'2.1.4'

# Loading the dataset as a DataFrame

In [ ]:
df_laptops = pd.read_csv("/content/laptops.csv")
df_laptops.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

# Q2. Records count
How many records are in the dataset?

In [ ]:
print(f"This dataset contain {df_laptops.shape[0]} records and {df_laptops.shape[1]} features.")

This dataset contain 2160 records and 12 features.


# Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [ ]:
print(f"This dataset contain {len(df_laptops['Brand'].unique())} laptop brands.")

This dataset contain 27 laptop brands.


# Q4. Missing values
How many columns in the dataset have missing values?

In [ ]:
nan_counts = df_laptops.isna().sum()
nan_counts[nan_counts > 0]

Storage type      42
GPU             1371
Screen             4
dtype: int64

In [ ]:
print(f"This dataset contain {len(nan_counts[nan_counts > 0])} columns with missing values.")

This dataset contain 3 columns with missing values.


# Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [ ]:
print(f"The maximum final price is {df_laptops[df_laptops['Brand'] == 'Dell']['Final Price'].max()}.")

The maximum final price is 3936.0.


# Q6. Median value of Screen
1. Find the median value of `Screen` column in the dataset.
2. Next, calculate the most frequent value of the same `Screen` column.
3. Use `fillna` method to fill the missing values in `Screen` column with the most frequent value from the previous step.
4. Now, calculate the median value of `Screen` once again.

Has it changed?

>Hint: refer to existing mode and median functions to complete the task.

In [ ]:
#1
print(f"The mean value of screen columns is {df_laptops.Screen.mean()}.")
#2
screen_mode = df_laptops.Screen.mode()[0]
print(f"The most frequent value of screen columns is {screen_mode}.")
#3
new_screen_values = df_laptops.Screen.fillna(screen_mode)
#4
print(f"Now, the mean value of screen columns with fill missing values is {new_screen_values.mean()}.")

The mean value of screen columns is 15.168112244897959.
The most frequent value of screen columns is 15.6.
Now, the mean value of screen columns with fill missing values is 15.168912037037037.


# Q7. Sum of weights
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns `RAM`, `Storage`, `Screen`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array y with values `[1100, 1300, 800, 900, 1000, 1100]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the sum of all the elements of the result?

>Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [ ]:
#1
df_laptops[df_laptops['Brand'] == 'Innjoo']

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [ ]:
#2
df_laptops.loc[df_laptops['Brand'] == 'Innjoo', ['RAM', 'Storage', 'Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [ ]:
#3
X = df_laptops.loc[df_laptops['Brand'] == 'Innjoo', ['RAM', 'Storage', 'Screen']].to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [ ]:
#4
X.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [ ]:
XTX = np.matmul(X.T, X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [ ]:
#5
XTX_inv = inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [ ]:
#6
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [ ]:
#8
w = np.matmul(XTX_inv, X.T) * y
w

array([[ 289.28183831, -163.28302487, -325.17111146,  134.62818528,
          52.44041848,   57.68446033],
       [  -1.21170793,    3.83576374,    1.00713386,   -1.59921842,
          -0.76387432,   -0.84026175],
       [ -96.49448601,   35.07282588,  137.12712814,  -27.18972029,
          -1.53546111,   -1.68900722]])

In [ ]:
#9
print(f"The sum of all the elements of the result is {w.sum()}")

The sum of all the elements of the result is 91.29988062995548
